FROM node:18 AS build
# Setting working directory.
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json ./
RUN npm install
# Copying source files
COPY . .

# Build files
RUN npm run build

FROM gcr.io/distroless/nodejs18-debian11:debug

ENV NODE_ENV=production
WORKDIR /usr/src/app
# Copying build from build container
COPY --from=build /usr/src/app .
# Running the app
EXPOSE 3000

CMD ["production-server/server.js"]